# Zuul

server:
  port: 8700
  tomcat:
    max-threads: 4

zuul:
  ignoredServices: "*"
  routes:
    user-core: /users/**

ribbon:
  eureka:
    enabled: true  

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
  