# User-core

spring:
  application:
    name: user-core

#zuul:
#  routes:
#    user-core: /users/**

server:
  port: 8000
  tomcat:
    max-threads: 4
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    net:
      deepuroy: DEBUG
    httpclient:
      wire: DEBUG

      
