# User-core

spring:
  application:
    name: user-core


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

---
spring:
  profiles: development

#Development profile
server:
  port: 8000
  tomcat:
    max-threads: 4
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

      
