# user-provider-google

spring:
  application:
    name: user-provider-google


apis:
  google:
    key: "Google API Key here"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true


# Information
info:
  name: "Google provider for user login"
    
---
spring:
  profiles: development
#Development profile
server:
  port: 8001
  tomcat:
    max-threads: 4
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true



  

 