# user-provider-google

spring:
  application:
    name: user-provider-google



server:
  port: 8001
  tomcat:
    max-threads: 4
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


apis:
  google:
    key: "Enter Google Key here"

# Information
info:
  name: "Google provider for user login"

  

 